# fly.toml app configuration file generated for profanity-bot on 2023-11-15T07:16:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "profanity-bot"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
